---
comment:
  image:
    repository: vlashm/comment
    tag: latest
  service:
    externalPort: 9292
    internalPort: 9292

post:
  image:
    repository: vlashm/post
    tag: latest
  service:
    externalPort: 5000
    internalPort: 5000

ui:
  image:
    repository: vlashm/ui
    tag: latest
  service:
    externalPort: 9292
    internalPort: 9292
  ingress:
    class: nginx
  postHost:
  postPort:
  commentHost:
  commentPort:

mongodb:
  auth:
    enabled: false
