version: '3.3'
services:
  post_db:
    image: mongo:${VERSION_MONGO}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
    env_file: .env

  ui:
    # build: ./ui
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORT}:9292/tcp
    networks:
      - front_net
    env_file: .env

  post:
    # build: ./post-py
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
    env_file: .env

  comment:
    # build: ./comment
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      back_net:
        aliases:
          - comment
      front_net:
        aliases:
          - comment
    env_file: .env

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - back_net
      - front_net
      - host

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - host

  mongo-exporter:
    image: percona/mongodb_exporter:0.32.0
    networks:
      - back_net
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
      - '--collect-all'

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.21.0
    user: root
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    driver: ${NETWORK_DRIVER}
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    driver: ${NETWORK_DRIVER}
    ipam:
      config:
        - subnet: 10.0.1.0/24
  host:
    driver: ${NETWORK_DRIVER}
