---
- name: Run image with app
  hosts: all
  become: true
  tasks:

  - name: Run container
    docker_container:
      image: vlashm/otus-reddit:1.0
      name: reddit
      ports:
        - 9292:9292
